spring.application.name=backend

server.port=8081

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/sabina_db
spring.datasource.username=sabina
spring.datasource.password=secret

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true